name: CI workflow

on: pull_request

jobs:
  ci-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: test
        run: npm test
  ci-e2e:
    runs-on: ubuntu-latest
    needs: [ci-unit]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Tests e2e
        run: npm run test:e2e:ci
