name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/chekout@v3
      - name: Install
        uses: npm ci
      - name: test
        uses: npm test

